services:
  easynews_as_indexer:
    image: ghcr.io/sanket9225/easynews_as_indexer
    environment:
      PORT: "8081"
      NEWZNAB_APIKEY: "testkey"
      EASYNEWS_USER: "your_easynews_username"
      EASYNEWS_PASS: "your_easynews_password"
      STRICT_MATCHING: "1"
      PUBLIC_URL: "http://10.10.10.5:8081"
    ports:
      - "8081:8081"
